apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    product: webapp
spec:
  project: default
  source:
    repoURL: https://github.com/camuzard/operators.git
    targetRevision: HEAD
    path: op1/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
     - CreateNamespace=true
    automated:
     selfHeal: true
     prune: true