apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    product: webapp
spec:
  project: request-counter
  source:
    repoURL: https://github.com/camuzard/django-app-helm.git
    targetRevision: HEAD
    path: django
    helm:
      values: |
        django:
          configureTemplates: true
        replicaCount: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
     - CreateNamespace=true
    automated:
     selfHeal: true
     prune: true